server:
  port: 9090

spring:
  application:
    name: loanInfo-service
  datasource:
    url: jdbc:mysql://localhost:3306/loans_master_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      example:
        LoanInfoService: DEBUG

  file:
    name: loaninfoservice.log
